site_name: Wiki 
nav:
  - Home: index.md
  - Network:
    - Ethernet: network/ethernet.md
    - TCP: network/tcp.md
    - IP: network/ip.md

  - Subject to study:
    - Ski : study/ski.md
  
theme: 
  name: readthedocs
  color_mode: dark
  highlightjs: true
