site_name: Wiki 
nav:
  - Home: index.md
  - Git: git.md
  - Cisco Conf:
    - VLAN et routage inter VLAN: cisco/interVlan.md
    - LACP: cisco/lacp.md
    
  - Network:
    - Ethernet TCP IP: network/ethernetTcpIp.md
    - SSH: network/ssh.md
    - DNS: network/dns.md
    - Routage:
      - RIP: network/routage/rip.md
      - OSPF: network/routage/ospf.md
      - BGP: network/routage/bgp.md
    - Snmp: network/Snmp.md
    - SDN:
      - Software defined network: network/SDN/sdn.md
      - P4 language: network/SDN/p4.md

  - Storage:
    - NAS et SAN : storage/san&nas.md

  - Divers:
    - hackathon Santé Conneté : study/hackathon.md
    - OCS Inventory: study/ocs.md
    - DensePose WIFI: study/densePose.md
  
theme: 
  name: readthedocs
  color_mode: dark
  highlightjs: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - git-revision-date-localized:
      type: timeago 
      locale: fr 