site_name: Wiki 
nav:
  - Home: index.md
  - Network:
    - Ethernet: network/ethernetTcpIp.md

  - Subject to study:
    - hackathon  Santé Conneté : study/hackathon.md
  
theme: 
  name: readthedocs
  color_mode: dark
  highlightjs: true
