site_name: Wiki 
nav:
  - Home: index.md
  - Git: git.md
  - Network:
    - Ethernet TCP IP: network/ethernetTcpIp.md

  - Travaux:
    - hackathon Santé Conneté : study/hackathon.md
  
theme: 
  name: readthedocs
  color_mode: dark
  highlightjs: true


plugins:
  - search
  - git-revision-date-localized:
      type: timeago 
      locale: fr 